; PlatformIO 项目配置文件
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
    +<main.cpp>
    -<mobile_web.cpp>

; 串口监视器波特率（和代码里 Serial.begin 的值要一致）
monitor_speed = 115200

; MAX30102 驱动库（SparkFun 出品，稳定可靠）
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2

[env:esp32_mobile_web]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
    -<main.cpp>
    +<mobile_web.cpp>
monitor_speed = 115200
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
